FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit kafka-python matplotlib pandas

COPY dashboard.py .

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
